package com.armutyus.cameraxproject.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB32631)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onPrimaryContainer = Color(0xFF410007)
val md_theme_light_secondary = Color(0xFF9C4140)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onSecondaryContainer = Color(0xFF410005)
val md_theme_light_tertiary = Color(0xFF9B4428)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onTertiaryContainer = Color(0xFF3A0A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF3E0500)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3E0500)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF524342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE9)
val md_theme_light_inverseSurface = Color(0xFF5E1608)
val md_theme_light_inversePrimary = Color(0xFFFFB3B0)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB32631)

val md_theme_dark_primary = Color(0xFFFFB3B0)
val md_theme_dark_onPrimary = Color(0xFF680010)
val md_theme_dark_primaryContainer = Color(0xFF91061D)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_secondary = Color(0xFFFFB3AF)
val md_theme_dark_onSecondary = Color(0xFF5F1316)
val md_theme_dark_secondaryContainer = Color(0xFF7E2A2A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_tertiary = Color(0xFFFFB59F)
val md_theme_dark_onTertiary = Color(0xFF5E1701)
val md_theme_dark_tertiaryContainer = Color(0xFF7C2D14)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3E0500)
val md_theme_dark_onBackground = Color(0xFFFFDAD3)
val md_theme_dark_surface = Color(0xFF3E0500)
val md_theme_dark_onSurface = Color(0xFFFFDAD3)
val md_theme_dark_surfaceVariant = Color(0xFF524342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C0)
val md_theme_dark_outline = Color(0xFFA08C8B)
val md_theme_dark_inverseOnSurface = Color(0xFF3E0500)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD3)
val md_theme_dark_inversePrimary = Color(0xFFB32631)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B0)


val seed = Color(0xFFA91E2B)